#define PI 3.14159265359

// SCREEN
#define DEFAULT_SCREEN_WIDTH 600
#define DEFAULT_SCREEN_HEIGHT 800

// DEBUG TEXT
#define FONT_PATH "assets/Inconsolata-Bold.ttf"

// TEST ASSETS
#define BALL_IMG_PATH "assets/ball.png"
#define HP_IMG_PATH "assets/life.png"
#define HP_IMG_SIZE 24

// LAYOUT
#define HP_PER_HEART 100
#define HP_UNIT_SIZE 24
#define ENEMY_HP_BAR_Y 0
#define MENU_SPACING 40
#define MENU_START_X 200
#define MENU_END_X DEFAULT_SCREEN_WIDTH - MENU_START_X
#define MENU_START_Y 350
#define MENU_FONT_GLOW_RATE 400
#define MENU_FONT_GLOW_FIXED 155
#define MENU_BOX_START_X DEFAULT_SCREEN_WIDTH / 4
#define MENU_BOX_START_Y DEFAULT_SCREEN_HEIGHT / 3
#define MENU_BOX_END_X 3 * DEFAULT_SCREEN_WIDTH / 4
#define MENU_BOX_END_Y 3 * DEFAULT_SCREEN_HEIGHT / 4
#define MENU_BOX_ALPHA 220

// PLAYER
// in seconds
#define PLAYER_SHOT_COOLDOWN 0.1
#define PLAYER_HP_BAR_Y DEFAULT_SCREEN_HEIGHT - HP_UNIT_SIZE

// OTHER
#define PARTICLE_DESTROY_ON_HIT_DELTA_RADIUS 180
#define PARTICLE_DESTROY_ON_HIT_DELTA_SPEED 4
#define PARTICLE_DESTROY_ON_HIT_DURATION 2
