#define PI 3.14159265359

// SCREEN
#define DEFAULT_SCREEN_WIDTH 600
#define DEFAULT_SCREEN_HEIGHT 800

// DEBUG TEXT
#define FONT_SIZE 20
#define FONT_PATH "assets/Inconsolata-Bold.ttf"

// TEST ASSETS
#define BALL_IMG_PATH "assets/ball.png"
#define HP_IMG_PATH "assets/life.png"
#define HP_IMG_SIZE 24

// LAYOUT
#define HP_PER_HEART 100
#define HP_UNIT_SIZE 24
#define ENEMY_HP_BAR_Y 0

// PLAYER
// in seconds
#define PLAYER_SHOT_COOLDOWN 0.1
#define PLAYER_HP_BAR_Y DEFAULT_SCREEN_HEIGHT - HP_UNIT_SIZE

// OTHER
#define PARTICLE_DESTROY_ON_HIT_DELTA_RADIUS 180
#define PARTICLE_DESTROY_ON_HIT_DELTA_SPEED 4
#define PARTICLE_DESTROY_ON_HIT_DURATION 2
